post_install() {
  glib-compile-schemas /usr/share/glib-2.0/schemas >/dev/null 2>&1 || true
  update-desktop-database -q >/dev/null 2>&1 || true
  gtk-update-icon-cache -qtf /usr/share/icons/hicolor >/dev/null 2>&1 || true
}

post_upgrade() {
  post_install
}

post_remove() {
  update-desktop-database -q >/dev/null 2>&1 || true
  gtk-update-icon-cache -qtf /usr/share/icons/hicolor >/dev/null 2>&1 || true
}
